### ISSUE TITLE
Fehler bei Übersetzungen "Add to Cart"-Button

### ISSUE THREAD

**Issue by MichaelKahl** [splendidinternet/Magento2_German_LocalePack_de_DE#1]
Nach dem Aufruf der Artikeldetailseite sind die Übersetzungen korrekt

![bildschirmfoto vom 2016-01-14 09 27 35](https://cloud.githubusercontent.com/assets/1192914/12319334/fb8689a6-baa1-11e5-98bc-4715a5209036.png)

Dann das Produkt in den Warenkorb legen. Der Button "In den Warenkorb legen" verändert sich zu "Adding.." , "Added" und dann zu "Add to Cart"

![bildschirmfoto vom 2016-01-14 09 28 04](https://cloud.githubusercontent.com/assets/1192914/12319372/3dd6f7d2-baa2-11e5-90bf-cf57dd8a4181.png)

Nach erneutem Laden der Seite stimmt die Übersetzung wieder.

**Comment by niclashoyer** [comment]
Mehr Infos zu js-Übersetzungen und Übersetzung allgemein:

https://gist.github.com/antonmakarenko/7538216
https://mage2.pro/t/topic/139
