### ISSUE TITLE
Von Sie auf Du umstellen und Update Safe bleibe

### ISSUE THREAD

**Issue by senders** [splendidinternet/Magento2_German_LocalePack_de_DE#105]
Was ist der beste Weg, die Sprachdatei zu überschreiben und trotzdem update safe zu bleiben?
Z.B. viele Sie Ansprachen in Du umzuwandeln.

**Comment by kkrieger85** [comment]
Hast du schon https://grafzahl.io/german-language-pack-du-anrede.html ausprobiert?

**Comment by senders** [comment]
Hallo,
danke für den Tip. Kannte ich noch nicht.
Allerdings kommt es mir nicht sehr vertrauenswürdig rüber.
Nur auf Grundlage 2.1.5 gebaut, also keine weiteren Updates.
Außerdem geht die Installation "Instructions Seite" nicht.
Schon Erfahrungen damit?

Die Frage ist auch noch mehr genereller Natur. 
Ich denke der eine oder andere mag bei einem String eine andere Übersetzung haben und will trotzdem update safe bleiben.

Da gibts doch bestimmt eine Lösung?!?

**Comment by kkrieger85** [comment]
Hi, 

mir ist das Paket während meiner Recherche nach einem "Du"-Paket für M1.9 aufgefallen. 
Habe bisher keine Erfahrungen damit gemacht. Vielleicht lohnen sich die 25€ um sich einiges an Übersetzungsarbeit zu sparen.

**Comment by oneserv-heuser** [comment]
@senders Meines Wissens gibt es keine Lösung für dieses Problem. Wenn du auf https://crowdin.com/project/magento-2 gehst (offizieles Übersetzungsprojekt von Magento), dann findest du dort 2 deutsche Sprachpakete: "German" und "German (informal)". SIeht für mich nicht so aus, als gäbe es da eine Lösung, als alles doppelt zu übersetzen. Wenn mal jemand ganz viel Zeit hat, kann man bestimmt auch noch ein zweites package anlegen (clone von diesem hier) und alles manuell auf Du umändern 😄

**Comment by oneserv-heuser** [comment]
Hab ein Ticket erstellt, vielleicht nehme ich mich/andere sich dessen an
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/issues/190

@niclashoyer Bitte dieses Ticket schließen
