### ISSUE TITLE
Whitespaces in csv

### ISSUE THREAD

**Issue by ktan88** [splendidinternet/Magento2_German_LocalePack_de_DE#113]
Nach dem Öffnen der de_DE.csv habe ich unnötige Whitespaces in der Datei.

**Comment by niclashoyer** [comment]
@ktan88 was verstehst du unter "unnötigen Whitespaces"? Gibt es da evtl. Leerzeichen am Ende von Zeilen oder soetwas?

Oder meinst du z.B. so etwas wie ab Zeile 7:

```
"
                            Allowable values: ""paypal"", ""primary"" (default), your_custom_value (a custom payment page style from your merchant account profile).
                        ","
                            Zulässige Werte: ""paypal"", ""primary"" (Standard), your_custom_value (ein benutzerdefinierter Zahlungsseiten-Stil von Ihrem Händler-Konto-Profil).
                        ",module,Magento_Paypal
"
```

Diese Zeilen sind leider genau so nötig, weil die auch tatsächlich so von Magento bzw. hier konkret dem PayPal-Modul mit diesen Leerzeichen so in der Übersetzung angefragt werden.

**Comment by ktan88** [comment]
@niclashoyer Ja genau so wie du es im Codeblock dokumentiert hast. So sieht leider irgendwie die ganze Datei aus.
Am Ende wäre ja sogar auszuhalten ;)
Wenn ich die Datei in PHPStorm oder einem normalen Editor öffnete wurde mir die Datei so zerbomt angezeigt.

**Comment by ktan88** [comment]
Hallo @niclashoyer,
das geht halt bis Zeile 154 so :/
Außerdem sind die folgenden Zeichen auch mit einem Space davor.
![grafik](https://user-images.githubusercontent.com/28091493/39252228-7c101f86-48a5-11e8-9ba9-15b69f15a267.png)

Hat es einen Grund warum bei manchen Übersetungen die Double Quotes fehlen?
Was benutzt ihr als Feldtrenner? Komma oder Tüddelchen?

Gruß Katha

**Comment by niclashoyer** [comment]
Also Trenner ist immer Komma. Die Anführungszeichen sollten nur da sein, wenn sie nötig sind (zumindest macht LibreOffice das bei mir so). Wir könnten sonst auch immer die Anführungszeichen reinmachen.

Ich hab grad nochmal geguckt, das mit den Leerzeichen vorne bis ca. Zeile 170 ist tatsächlich so und muss leider auch so bleiben.

Im PHP steht dann halt sowas:

![bildschirmfoto von 2018-04-25 16-39-37](https://user-images.githubusercontent.com/175808/39253058-4a1533ac-48a7-11e8-88ac-bb13519651f8.png)

das heißt Magento will den String schon mit Leerzeichen übersetzen, so dass wir die Leerzeichen dann 1 zu 1 in die CSV übernehmen müssen.

Warum dein Editor da jetzt die Zeilen so komisch markiert weiß ich leider nicht :disappointed:

**Comment by niclashoyer** [comment]
Hier nochmal Screenshots von den Einstellungen zum Laden/Speichern, die wir für LibreOffice benutzen:

![bildschirmfoto von 2018-04-25 16-42-45](https://user-images.githubusercontent.com/175808/39253263-c8b6e0de-48a7-11e8-8912-9830b9fd5683.png)
![bildschirmfoto von 2018-04-25 16-42-15](https://user-images.githubusercontent.com/175808/39253266-c9645336-48a7-11e8-8e81-32dba145039f.png)

**Comment by ktan88** [comment]
Hi @niclashoyer,
stimmt, Magento ist da nicht ganz so clever.
Search and Replace statt id für translations ist schon nicht so das hellste ;)
Ok dann macht das alles Sinn.
Somit, closed.
