### ISSUE TITLE
Rabattcode vs. Gutscheincode

### ISSUE THREAD

**Issue by niclashoyer** [splendidinternet/Magento2_German_LocalePack_de_DE#119]
Benennung ist nicht einheitlich

**Comment by oneserv-heuser** [comment]
@niclashoyer What exactly is the problem here?
Should everything be converted to "Rabattcode" or "Gutscheincode"?
The word "Rabattcode" was used 2 times, "Gutscheincode" 26 times.
Accordingly, I would lean towards "Gutscheincode".

**Comment by niclashoyer** [comment]
Yes, I think "Gutscheincode" is fine
