### ISSUE TITLE
'so niedrig wie' is not a suitable translation for as low as

### ISSUE THREAD

**Issue by dakira** [splendidinternet/Magento2_German_LocalePack_de_DE#120]
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/blob/208fc97776643e2047ee9ca179d6bdcb34afc354/de_DE.csv#L1320

Nobody would ever say this. The common German translation would be "Ab". I'll create a PR if you're fine with the change.

**Comment by turbobasti** [comment]
Soweit ich gesehen habe steht das immer noch drin. Ich habe bis jetzt auch kein Weg gefunden das zu überschreiben außer hart in der CSV.
