### ISSUE TITLE
Probleme mit Übersetzungen im Magento Code?

### ISSUE THREAD

**Issue by daniel-rosengarten** [splendidinternet/Magento2_German_LocalePack_de_DE#14]
@felixbuechner 
Hier Fundstellen von Strings, die im Sprachpaket enthalten sind, im Backend aber nicht entsprechend übersetzt werden.
### Umsatz > Bestellungen

· per page,pro Seite
· Complete,Vollständig und Processing,Verarbeitung ... (wohl sämtliche Status an der entsprechenden Stelle)
· Select Items,Artikel auswählen 
### Produkte > Katalog > Neues Produkt > Design

1 column,1 Spalte ... Empty,Leer (sämtliche Bezeichner für Seiten-Layouts)
### Kunden > All Customers > Neuer Kunde

Male,Männlich;Female,Weiblich;Not Specified,Keine Angabe
### Kunden > Now Online

We couldn't find any records.,Es wurden keine Einträge gefunden.
### Inhalt > Seiten

Select,Auswählen
### System > Importoptionen

This is a required field.,Dies ist ein Pflichtfeld
### System > Import-Historie

"Created: %1, Updated: %2, Deleted: %3","Erstellt: %1, Update: %2, Gelöscht: %3"
### System > Cache-Management

Layout building instructions.,Layout-Bauanleitung.
Und alle weiteren Beschreibungen der unterschiedlichen Caches.
### eingeblendete Meldung

One or more of the Cache Types are invalidated: %1.,Eine oder mehrere der Cache-Typen sind ungültig. %1

**Comment by felixbuechner** [comment]
@daniel-rosengarten Hast du hier auf genaue Schreibweise geachtet? Also es steht genau so im Sprachpaket wie auch im Backend?

**Comment by daniel-rosengarten** [comment]
@felixbuechner 
Ja, genau: ich habe mich am Backend orientiert (String aus dem Admin-Panel kopiert und im Sprachpaket gesucht). Aber ich bin jetzt nicht den Code durchgegangen. Gerade an den Stellen, an denen Platzhalter mit Werten befüllt werden, müsste da natürlich noch ein Blick reingeworfen werden. (Aber ich habe keine Ahnung von der Magento 2 Codestruktur.)

**Comment by felixbuechner** [comment]
@niclashoyer Guckst du dir die Stellen im Code an?

**Comment by niclashoyer** [comment]
Die Übersetzungen sind in der 2.2 jetzt drin
