### ISSUE TITLE
Static Content Deploy de_DE magento 2.3

### ISSUE THREAD

**Issue by ktownmods** [splendidinternet/Magento2_German_LocalePack_de_DE#140]
Hey bei dem schritt php bin/magento setup:static-content:deploy de_DE kommt folgender fehler:

NOTE: Manual static content deployment is not required in "default" and "developer" modes.
  In "default" and "developer" modes static contents are being deployed automatically on demand.
  If you still want to deploy in these modes, use -f option: 'bin/magento setup:static-content:deploy -f'

was kann ich da machen?

**Comment by sprankhub** [comment]
`production` Mode nutzen oder aber wie die Fehlermeldung schon sagt `bin/magento setup:static-content:deploy -f` nutzen.

**Comment by niclashoyer** [comment]
@sprankhub danke! Hab `-f` in der Readme ergänzt. Generell ist der `production`-Mode natürlich sinnvoller (zumindest live).
