### ISSUE TITLE
Translation for checkout error "A server error stopped your order from being placed..."

### ISSUE THREAD

**Issue by Lukas1Komarek** [splendidinternet/Magento2_German_LocalePack_de_DE#150]
"A server error stopped your order from being placed. Please try to place your order again."

possible translation:
"Aufgrund eines Fehlers konnte Ihre Bestellung nicht aufgegeben werden. Bitte versuchen Sie es erneut."

**Comment by jg-development** [comment]
ist inzwischen enthalten ... könnte geschlossen werden:

Ein Serverfehler verhinderte, dass Ihre Bestellung aufgegeben wurde. Bitte versuchen Sie, Ihre Bestellung erneut aufzugeben.
