### ISSUE TITLE
Autoload error

### ISSUE THREAD

**Issue by walterm23** [splendidinternet/Magento2_German_LocalePack_de_DE#160]
Hi there,

after Update from Magento CE 2.3.2 to 2.3.3 i get an Autoload Error:
"Language 'splendid_de_de' from 'xxx/app/i18n/splendid/de_DE' has been already defined in 'xxx/vendor/splendidinternet/mage2-locale-de-de'.

I tried a log in via SSH to restore the backup, but the bin/magento backup/restore commands show the same error.

Any suggestions?

**Comment by niclashoyer** [comment]
It should be working on Magento 2.3.3. The `has been already defined` message suggests that the module is loaded twice. Do you also have the module in `/app/code`?

Another thing you could try to get the commands working again is manually cleaning the `generated` folder and the cache:

```
# inside magento directory
rm -rf generated
rm -rf var/cache/*
```

If the module is *not* loaded twice, your commands should be working again. If you still get the error, try removing the module from vendor temporarily:

```
rm -rf vendor/splendidinternet/mage2-locale-de-de
```

After that check if your shop works again and try to reinstall the module using composer.
