### ISSUE TITLE
German keys and no translations used

### ISSUE THREAD

**Issue by mcmulman** [splendidinternet/Magento2_German_LocalePack_de_DE#165]
splendidinternet/mage2-locale-de-de/de_DE.csv:7345 - 7358 
English keys and commas should be used.

**Comment by niclashoyer** [comment]
It seems that the lines 7330 to 7343 are the corresponding keys. I'll take care of that.

**Comment by mcmulman** [comment]
Thanks!

**Comment by niclashoyer** [comment]
Fixes in 1.56.1
