### ISSUE TITLE
Please update for Magento 2.4.0

### ISSUE THREAD

**Issue by Emanuel-23** [splendidinternet/Magento2_German_LocalePack_de_DE#169]
Please update the package  for Magento 2.4.0 and PHP 7.4

**Comment by jg-development** [comment]
+1

**Comment by oneserv-heuser** [comment]
Yes please! Just updatet to Magento 2.4.0 and now I cannot use this package anymore because of version clashes with magento/framework.

**Comment by jg-development** [comment]
a check with phpcompat shows no problems with php 7.4 ... as expected

**Comment by niclashoyer** [comment]
1.60.0 is out

**Comment by oneserv-heuser** [comment]
@niclashoyer When will it be released on packagist?

**Comment by Emanuel-23** [comment]
@niclashoyer 
Looks like the new version see [1.60.0 tag ](https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/blob/1.60.0/composer.json) still requires 
`"magento/framework": "^100.0.0 || ^101.0.0 || ^102.0.0 || ^103.0.0"` and so does not support `"magento/framework": "^104.0.0" `

moreover the version has not been changed neither.

Am I missing something?

**Comment by niclashoyer** [comment]
yes, sorry, 1.61.0 is out with `104.0.0` added, but please bear in mind that we are still in the process of translating the new strings, so there will be translations missing.

**Comment by niclashoyer** [comment]
@oneserv-heuser thanks for the hint. Packagist should have picked up the new versions automatically. I'll have to look into it.

**Comment by Emanuel-23** [comment]
@niclashoyer thanks for your lightning fast response. Unfortunately the version has not been bumped within composer, so i assume this might produce the problems with packagist :pensive:

**Comment by niclashoyer** [comment]
:1st_place_medal: that was it! Yes, we forgot to change the version in composer.json. So I fixed that and released a new version 1.62.0 that should work now (it is already on Packagist, just checked).
