### ISSUE TITLE
In der Kurzbeschreibung erscheint "Keine:" vor dem Text.

### ISSUE THREAD

**Issue by Moppelfett** [splendidinternet/Magento2_German_LocalePack_de_DE#171]
Nach der Installation erscheint nach dem Sprachwechsel im Dropdown in der Kurzbeschreibung der Produkte das Wort "Keine:" vor dem Inhalt.
![issue](https://user-images.githubusercontent.com/12279931/105470871-62f6ea00-5c9a-11eb-9f8a-f188b5288d5f.jpg)

Ist das ein Magento Bug oder ein Fehler der LocalePack Extension?
Es ist ein frisch installiertes Magento 2.4.1.

**Comment by Moppelfett** [comment]
Danke für die Antwort.
Es handelt sich um ein Drittanbieter Template.
Ich werde mich auf die Suche machen und das fixen.

Besten Dank!

**Comment by Moppelfett** [comment]
Die Lösung ist folgende Änderung in der Datei attribute.phtml
Pfad: app/design/frontend/THEME VENDOR/THEME ORDNER/Magento_Catalog/templates/product/view

Suche nach
<?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?>: </strong><?php endif; ?>

Ersetze es hiermit:
<?php if ($_attributeLabel != 'none' && $_attributeLabel != 'Keine'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?>: </strong><?php endif; ?>

**Comment by Moppelfett** [comment]
Die Lösung ist folgende Änderung in der Datei attribute.phtml
Pfad: app/design/frontend/THEME VENDOR/THEME ORDNER/Magento_Catalog/templates/product/view

Suche nach
`<?php if ($_attributeLabel != 'none'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?>: </strong><?php endif; ?>`

Ersetze es hiermit:
`<?php if ($_attributeLabel != 'none' && $_attributeLabel != 'Keine'): ?><strong class="type"><?php /* @escapeNotVerified */ echo $_attributeLabel?>: </strong><?php endif; ?>`

**Comment by oneserv-heuser** [comment]
@niclashoyer Can you close this issue please as it is no issue with this package.
