### ISSUE TITLE
Releases 1.64.0 and 1.65.0 not published to packagist

### ISSUE THREAD

**Issue by oneserv-heuser** [splendidinternet/Magento2_German_LocalePack_de_DE#177]
See https://packagist.org/packages/splendidinternet/mage2-locale-de-de
The latest version there is 1.63.0, which means it's not possible to update this package to 1.64.0 or 1.65.0 via composer.

**Comment by niclashoyer** [comment]
sorry, fixed now. The 1.66.0 is the latest released version
