### ISSUE TITLE
Future of this repository

### ISSUE THREAD

**Issue by oneserv-heuser** [splendidinternet/Magento2_German_LocalePack_de_DE#182]
Hey ho!

It doesn't look like that this repostitory actively maintained anymore. Latest commit was was on 06.04.2021 and there are many issues open, some since 2018. I'd be happy to fork, release and maintain this repository if it's okay for @splendidinternet.

**Comment by niclashoyer** [comment]
@oneserv-heuser thanks for the reach out! The repository is still maintained. The activity depends on our daily workload, but we are open for help! The best way to contribute is to fork/add pull requests. We'll merge PRs pretty quickly.

**Comment by oneserv-heuser** [comment]
@niclashoyer  Thats nice to hear, then I'll try to fix a few issues the next days!
