### ISSUE TITLE
graphic issue with widgets and buttons

### ISSUE THREAD

**Issue by MYITWORKS** [splendidinternet/Magento2_German_LocalePack_de_DE#21]
After installing there is a problem in the widget-area "what's new" of the sample-data-shop

as you see in the picture the text "Inkl. 7% MwSt., exkl. Versandkosten" cant be seen completely but is overlayed by the "zum warenkorb hinzufügen" button

![german locale uberlagerung](https://cloud.githubusercontent.com/assets/18720799/14909562/5cfb2e44-0de5-11e6-981e-3332ff127ad1.JPG)

I already cleard caches, restartet ubuntu server. stays the same.

**Comment by kkrieger85** [comment]
@MYITWORKS Do you have n public URL to check this? 
I think this is more a css-issue than a translation issue.

**Comment by niclashoyer** [comment]
We did see the same problems, but it was after using [magesetup2](https://github.com/firegento/firegento-magesetup2), which adds `Inkl. xx MwSt., exkl. Versandkosten` underneath the price, so it may be an issue with that.

**Comment by MYITWORKS** [comment]
Hi there,

Sorry, just a dev-system with no public URL.

But you are completely right. I added magesetup2 too.

I will create an issu there.

Here the code of both elements (just if you are curious):

`<span class="tax-details">Inkl. 7% MwSt.<span class="tax-separator">, </span><span class="shipping-cost-details">exkl. <a href="http://192.168.10.134/lieferung">Versandkosten</a></span></span>
`

`<div class="product-item-actions">
                                                                                    <div class="actions-primary">
                                                                                                                                                                                                                    <button class="action tocart primary" data-post="{&quot;action&quot;:&quot;http:\/\/192.168.10.134\/checkout\/cart\/add\/uenc\/aHR0cDovLzE5Mi4xNjguMTAuMTM0Lw,,\/product\/10\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;10&quot;,&quot;uenc&quot;:&quot;aHR0cDovLzE5Mi4xNjguMTAuMTM0Lw,,&quot;}}" type="button" title="Zum Warenkorb hinzufügen">
                                                            <span>Zum Warenkorb hinzufügen</span>
                                                        </button>
                                                                                                                                                </div>
                                                                                                                            <div class="actions-secondary" data-role="add-to-links">
                                                                                                    <a href="#" data-post="{&quot;action&quot;:&quot;http:\/\/192.168.10.134\/wishlist\/index\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;10&quot;,&quot;uenc&quot;:&quot;aHR0cDovLzE5Mi4xNjguMTAuMTM0Lw,,&quot;}}" class="action towishlist" data-action="add-to-wishlist" title="Zur Wunschliste hinzufügen">
                                                        <span>Zur Wunschliste hinzufügen</span>
                                                    </a>
                                                                                                                                                                                                        <a href="#" class="action tocompare" data-post="{&quot;action&quot;:&quot;http:\/\/192.168.10.134\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;10&quot;,&quot;uenc&quot;:&quot;aHR0cDovLzE5Mi4xNjguMTAuMTM0Lw,,&quot;}}" title="Zur Vergleichsliste hinzufügen">
                                                        <span>Zur Vergleichsliste hinzufügen</span>
                                                    </a>
                                                                                            </div>
                                                                            </div>`

**Comment by niclashoyer** [comment]
great, so I'll close it then
