### ISSUE TITLE
%1,1% - Zeile 87

### ISSUE THREAD

**Issue by bh-ref** [splendidinternet/Magento2_German_LocalePack_de_DE#27]
Hallo, vielen Dank für die Übersetzung!

In Zeile 87 übersetzt ihr "%1" mit "1%", das führt im Backend von Magento 2.1 beim Bearbeiten der Produkte zu einer falschen Übersetzung, da die Namen der im Attributset definierten Produktgruppen dann mit "1%" dargestellt werden: 

![image](https://cloud.githubusercontent.com/assets/15156912/16485479/4313d430-3ebf-11e6-919e-c92815ae70a6.png)

Wenn die Zeile entfernt wird und der cache gecleant wird, werden die Namen wie erwartet geladen.

(abgesehen davon, wieso wird "%1" mit "1%" übersetzt?)

**Comment by niclashoyer** [comment]
Das ist wahrscheinlich ein Übersetzungsfehler. Wenn man die Zeile einfach rausnimmt ist alles gut? Dann werden wir das beim nächsten Release einfach entfernen.

**Comment by bh-ref** [comment]
Alles klar. Wenn die Zeile rausgenommen wird, ist alles gut, genau. Merci für das schnelle Feedback.
