### ISSUE TITLE
Fehlende Übersetzung?

### ISSUE THREAD

**Issue by s1m0nde** [splendidinternet/Magento2_German_LocalePack_de_DE#34]
Hi!
In der Warenkorb Vorschau steht der Button auf "View cart". Ich weiß nicht, wie ich das selber ändern kann. 
Außerdem ist die Nachricht auf englisch, wenn man etwas aus dem Warenkorb entfernt. Ich hab es alles auf dem Screenshot. Wie kann ich sowas ggf auch manuel korrigieren? 
LG & Vielen Dank!
![ubersetzung](https://cloud.githubusercontent.com/assets/6803289/17404703/fe458aa6-5a5c-11e6-843c-2cd4fed8995d.png)

**Comment by peterhirn** [comment]
JS muss teilweise manuell korrigiert werden:

- `app/code/Magento/Catalog/view/frontend/web/js/catalog-add-to-cart.js`
- `app/code/Magento/Checkout/view/frontend/web/js/model/shipping-rates-validator.js`
- `app/code/Magento/Checkout/view/frontend/web/js/view/minicart.js`

`View Cart` sollte eigentlich passen, heißt in der 2.0.x `View and edit cart,Warenkorb ansehen und bearbeiten`. Schau dir dazu mal die `app/code/Magento/Checkout/view/frontend/web/template/minicart/content.html` an.

Mit `grep` findet man meistens die passenden files.

**Comment by grasdaggel** [comment]
Die Übersetzungen zeigen bei der Kopie ins eigene Theme keine Wirkung. Magento2-Bug?

**Comment by MichaelKahl** [comment]
Übersetzugen sind drin
