### ISSUE TITLE
Änderung vornehmen

### ISSUE THREAD

**Issue by s1m0nde** [splendidinternet/Magento2_German_LocalePack_de_DE#36]
Hi!
Wenn ich in der de_DE Datei etwas ändern will (Öffnen mit excel, bearbeiten, speichern, online ersetzen), bekomme ich auf meiner Seite nur eine Fehlermeldung bis ich die Originaldatei wieder einspiele. Ich muss unbedingt einen Ausdruck ändern. Wie kann ich das machen ohne einen Fehler zu produzieren?

Vielen Dank und LG!

**Comment by grasdaggel** [comment]
Nicht mit Excel öffnen, sondern mit einem anderen Text-Editor. Das hilft. Beim Upload auf korrekte Encodierung (UTF-8) achten.

**Comment by niclashoyer** [comment]
LibreOffice funktioniert auch sehr gut: https://de.libreoffice.org/

**Comment by s1m0nde** [comment]
Okay danke! Reicht es denn aus, die Datei zu ersetzen, wenn ich eine Zeile hinzugefügt habe, oder muss ich in SSH noch einen Befehl ausführen?

**Comment by grasdaggel** [comment]
Wenn deine Entwicklungsumgebung im Dev-Modus ist reicht es aus, wenn du den Cache einmal komplett löschst. Im Live-Modus musst du noch zusätzlich `php bin/magento setup:static-content:deploy de_DE`ausführen.

**Comment by s1m0nde** [comment]
PS: 
http://www.convertcsv.com/csv-viewer-editor.htm
Da ich auch mit OpenOffice Calc gescheitert bin, habe ich nach einem Online Editor gesucht.
Ich habe die Datei hochgeladen, bearbeitet und mit der Einstellung EOL: LF gespeichert und heruntergeladen. So hat es geklappt (vor allem ohne noch ein Programm zu installieren).

Vielen Dank für eure Hinweise!

PS: Ich hab noch ein anderes Problem. Vielleicht hat jemand einen Tipp. Über google finde ich keine Lösung.
Ich habe konfigurierbare Produkte. Je nach Konfiguration gibt es verschiedene Preise. Ich würde also damit rechnen, dass beim Konfigurationsprodukt beim Preis steht "Ab xxxx€" Stattdessen steht dort nur der Preis, den ich bei der ersten  Einrichtung des Produkts eingegeben habe. Weiß jemand, ob das ein Bug ist, ob das einfach nicht anders geht oder wie man das einstellen kann?

**Comment by grasdaggel** [comment]
Am besten fragst du mal auf magento.stackexchange.com.
