### ISSUE TITLE
Update für 2.1.0-rc3?

### ISSUE THREAD

**Issue by grasdaggel** [splendidinternet/Magento2_German_LocalePack_de_DE#41]
Mit Magento2.1.0-rc3 sind übersetzbare E-Mail-Template-Strings hinzugefügt worden. Diese können nun per CSV übersetzt werden.

Ein Update für Magento2.1.0-rc3 wäre sehr wünschenswert.

**Comment by felixbuechner** [comment]
Das Update ist inzwischen im Sprachpaket enthalten.
