### ISSUE TITLE
Bestelllstatus vs. Bestellzustand

### ISSUE THREAD

**Issue by niclashoyer** [splendidinternet/Magento2_German_LocalePack_de_DE#47]
Wir haben im Moment "status" und "state" mit "Bestellstatus" übersetzt. Da die Unterscheidung aber wichtig ist, sollten wir diese Begriffe auch unterschiedlich übersetzen.

z.B.
status -> Bestellstatus
state -> Bestellzustand

**Comment by jBOKA** [comment]
+1 nicht noch mehr Verwirrung was die beiden Begriffe angeht!

**Comment by felixbuechner** [comment]
Ist jetzt entsprechend angepasst.
