### ISSUE TITLE
Checkout Fortschritte sind inzwischen korrigiert

### ISSUE THREAD

**Issue by jBOKA** [splendidinternet/Magento2_German_LocalePack_de_DE#48]
Der Abschnitt in der README _Fortschritte im Checkout nicht übersetzt_ kann entfernt werden. Ich habe mal in den fix geschaut und spätestens seit 2.1.0 sind die änderungen auch im Magento repo das ich über composer bezogen habe. Inzwischen ist ja 2.1.2 raus. Sollte also passen

**Comment by niclashoyer** [comment]
Ist aus der Readme jetzt raus
