### ISSUE TITLE
Bitte in den Marketplace stellen!

### ISSUE THREAD

**Issue by muroshi** [splendidinternet/Magento2_German_LocalePack_de_DE#53]
Hier nützt das Ding nicht viel.

**Comment by latenzio** [comment]
Das stimmt nicht. Man kann es nur nicht über das Backend von Magento2 installieren. Auf GitHub ist es tatsächlich viel besser aufgehoben.

**Comment by niclashoyer** [comment]
Wir sind gerade dabei das Sprachpaket auch bei Magento 2 in den Marketplace einzustellen. Allerdings müssen wir da jetzt noch die diversen Hürden bei der technischen sowie marketingmäßigen Prüfung überstehen.

Die Aktualisierungen fahren wir auf GitHub jedenfalls schneller rein.

**Comment by niclashoyer** [comment]
Ist jetzt auch im Marketplace:

https://marketplace.magento.com/splendidinternet-mage2-locale-de-de.html

Wir versuchen weiterhin dies dort möglichst aktuell zu halten. Die neuesten Versionen gibt es aber nach wie vor hier im Repo.
