### ISSUE TITLE
Deutsches Backend

### ISSUE THREAD

**Issue by bbtimx** [splendidinternet/Magento2_German_LocalePack_de_DE#54]
Hallo,
wie kann ich denn das Backend auf deutsch umstellen? Es sind nur sehr wenige Texte ins deutsche übersetzt. Im Frontend sieht es dagegen sehr gut aus.
Installiert habe ich es manuell laut Anleitung,

Danke

**Comment by latenzio** [comment]
1. Deine Frage bezieht sich auf Magento2 im Allgemeinen und nicht auf dieses Language-Pack.
2. Wenn wenige Texte ins Deutsche übersetzt sind, dann hast Du bereits Dein Backend auf deutsch eingestellt. 🎤 💧

**Comment by bbtimx** [comment]
zu 1. Na aber Magento 2 gibt es doch standardmäßig nicht auf deutsch, also dachte ich das dieses Language Pack auch das Backend übersetzt und ich nur irgendwas falsch eingestellt habe
zu 2. Es sind nur sehr wenige vereinzelte Begriffe auf deutsch, diese können aber auch im Zusammenhang mit anderern Extensions übersetzt sein.
Im Dashboard ist zum Beispiel nicht ein einziges Wort auf deutsch

**Comment by niclashoyer** [comment]
Im Dashboard sollte eigentlich alles auf Deutsch sein. Die Sprache kannst du rechts oben bei deinem Account-Namen umstellen in deinen "Account Settings":

![bildschirmfoto von 2017-01-05 15-33-10](https://cloud.githubusercontent.com/assets/175808/21684034/4877d214-d35c-11e6-9dac-ed0f4a5f0b69.png)

**Comment by bbtimx** [comment]
Vielen Dank,

das war genau die Information die ich gebraucht habe!
