### ISSUE TITLE
Certain Translation String causes Magento 2 Errors

### ISSUE THREAD

**Issue by jmackiol-dotsource** [splendidinternet/Magento2_German_LocalePack_de_DE#57]
Line 7779 ("ui/grid/filters/elements/select,UI / Raster/ Filter / Elemente / Auswählen") causes bad requests in Magento 2 EE and in rare instances cause the cleaning of static content to remove the complete installation:

Request generated in Catalog / Product grid: HOST/static/adminhtml/Magento/backend/de_DE/UI%20/template/%20Raster/%20Filter%20/%20Elemente%20/%20Auswählen.html Failed to load resource: the server responded with a status of 404 (Not Found)

![image](https://cloud.githubusercontent.com/assets/12070095/22507406/bc3c6dd4-e885-11e6-8830-7c692d4117e3.png)
![image](https://cloud.githubusercontent.com/assets/12070095/22507440/e72f2cc0-e885-11e6-904c-e6fb8725d22d.png)

If I remove the line in question, the request is generated correctly and the Magento 2 self destruction (https://github.com/magento/magento2/issues/8017) could not be replicated (yet).

**Comment by felixbuechner** [comment]
This line has been removed.
