### ISSUE TITLE
Neues Produkt - Hälfte Englisch???

### ISSUE THREAD

**Issue by special-trends** [splendidinternet/Magento2_German_LocalePack_de_DE#58]
Hallo,

habe ich etwas falsch gemacht oder warum werden so viele Merkmale beim Anlegen eines neuen Produktes immer noch auf Englisch angezeigt (z.B. enable product / price) ? 
![de_en](https://cloud.githubusercontent.com/assets/25538592/22609983/9c0c5896-ea63-11e6-8d7f-2c1631d8d706.JPG)

**Comment by MichaelKahl** [comment]
Das sind Produktattribute. Hier müssen die Labels angepasst werden
