### ISSUE TITLE
Pfad-Übersetzung führt zu falschen Pfaden unter pub/static

### ISSUE THREAD

**Issue by lfritsche** [splendidinternet/Magento2_German_LocalePack_de_DE#61]
Folgende Zeile:
`ui/grid/filters/elements/select,UI / Raster/ Filter / Elemente / Auswählen``
sollte dringend aus der de_DE.csv entfernt werden.
Sie übersetzt ungewollt den Pfad und beinhaltet zudem Leerzeichen...

Genaueres siehe hier:
https://github.com/magento/magento2/issues/8534

**Comment by niclashoyer** [comment]
@felixbuechner 
kannst du die entfernen?

**Comment by felixbuechner** [comment]
@niclashoyer ist entfernt
