### ISSUE TITLE
Fehlender Punkt am Ende des Satzes

### ISSUE THREAD

**Issue by elxa** [splendidinternet/Magento2_German_LocalePack_de_DE#64]
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/blob/master/de_DE.csv#L8333
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE/blob/master/de_DE.csv#L6233

**Comment by felixbuechner** [comment]
Beim ersten Satz ist der Punkt da, das zweite ist gar kein Satz.
