### ISSUE TITLE
Nach Einspielen der Übersetzung schleicht sich das Wort "KEINE" in die Kurzbeschreibung 

### ISSUE THREAD

**Issue by Moppelfett** [splendidinternet/Magento2_German_LocalePack_de_DE#65]
Nachdem ich auf einer frischen Magento 2.1.5 mit Custom Template das German package einspiele, taucht in der Kurzbeschreibung der Artikel das Wort "KEINE" auf.
Wie bekomme ich diesen Bug gefixt?
Danke vorab für jede Hilfe.

![bildschirmfoto 2017-03-13 um 10 17 54](https://cloud.githubusercontent.com/assets/12279931/23848272/bb1afcd4-07d6-11e7-94cf-0d19ddaf54c5.png)

**Comment by niclashoyer** [comment]
Um welches Theme handelt es sich? Wichtig wäre zu wissen, was dort im Original, also auf Englisch steht.

**Comment by Moppelfett** [comment]
Auf der englischen Ansicht, taucht dieser Fehler nicht auf.

![bildschirmfoto 2017-03-13 um 12 51 49](https://cloud.githubusercontent.com/assets/12279931/23853221/e5a39b36-07eb-11e7-8c00-34fec305acb4.png)

In Englisch wird laut der de_DE.csv das Wort "None" übersetzt.

**Comment by niclashoyer** [comment]
Hm da müsste man wohl in die Programmierung des Themes gehen. Evtl. ist da sowas drin wie

```php
if ($name !== 'None') {
    /* ... */
}
```

und `$name` wird vorher übersetzt, so dass dann etwas angezeigt wird.
Ist aber nur eine Vermutung.

**Comment by niclashoyer** [comment]
Ah ich sehe gerade das ist ein Problem in Magento selbst:

https://github.com/magento/magento2/issues/5886

**Comment by Moppelfett** [comment]
Welche Lösung ist dauerhaft die beste?

**Comment by niclashoyer** [comment]
So lange Magento kein Update mit dem Fix rausbringt kann man nur auf temporäre Lösungen mit Workarounds setzen. In dem verlinkten Issue wird folgendes vorgeschlagen:

Mit einer Extension die Datei `catalog_product_view.xml` erweitern um folgendes XML:

```xml
<referenceBlock name="product.info.overview">
  <arguments>
    <argument name="at_label" xsi:type="string">none</argument>
  </arguments>
</referenceBlock>
```

Alternativ kann man natürlich auch die Datei direkt in `vendor` bzw. `app/code` anpassen. Dann ist nach einem Update aber der Workaround wieder weg:

In der Datei `app/code/Magento/Catalog/view/frontend/layout/catalog_product_view.xml` in folgender Zeile

```xml
<argument name="at_label" translate="true" xsi:type="string">none</argument>
```

den Abschnitt `translate="true"` rausnehmen.

**Comment by Moppelfett** [comment]
Würde gerne den ersten Vorschlag umsetzen.
Wie lautet der Pfad zu der gemeinten catalog_product_view.xml?
Es gibt die Datei sehr oft in den Verzeichnissen.

**Comment by niclashoyer** [comment]
Wir haben das bis jetzt immer gelöst, in dem wir in das verwendete Theme einfach die oben genannte Datei hinzugefügt haben, also z.B. (`Vendor/Theme` entsprechend ersetzen):

    app/design/frontend/Vendor/Theme/Magento_Catalog/layout/catalog_product_view.xml

mit folgendem Inhalt:

```xml
<?xml version="1.0"?>
<page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
	<body>
		<referenceBlock name="product.info.overview">
			<arguments>
				<argument name="at_label" xsi:type="string">none</argument>
			</arguments>
		</referenceBlock>
	</body>
</page>
```

**Comment by Moppelfett** [comment]
Mit eurer Hilfe habe ich es lösen können.

Vielen Dank!

**Comment by niclashoyer** [comment]
Wird endlich gefixt sein mit Magento 2.2.2. Bis diese Version raus ist bleibt das Issue hier offen.

**Comment by cedricziel** [comment]
Version 2.2.2 is released.
