### ISSUE TITLE
Übersetzung von "Delivery Time" bleibt aus

### ISSUE THREAD

**Issue by Moppelfett** [splendidinternet/Magento2_German_LocalePack_de_DE#66]
Gruß in die Runde,

leider übersetzt das Paket bei meinem custom Template nicht den Punkt "Delivery Time".
Da ich einen shop in zwei Sprachen aufbaue, kann ich keine Änderung in der XML durchführen da es auf der englischen Seite ebenfalls in Deutsch angezeigt wird.

Unter "Details" weiter unten wird es übersetzt, nur nicht unter der Kurzbeschreibung.

In der de_DE.csv ist 
Delivery Time,Lieferzeit
hinterlegt.
Die Übersetzung bleibt aber leider aus.

In der Catalog_delivery_info.xml steht folgendes:
`<arguments>
                <argument name="at_call" xsi:type="string">getDeliveryTime</argument>
                <argument name="at_code" xsi:type="string">delivery_time</argument>
                <argument name="css_class" xsi:type="string">delivery_time</argument>
                <argument name="at_label" xsi:type="string">Delivery Time </argument>
                <argument name="add_attribute" xsi:type="string">itemprop="delivery_time "</argument>
`

Irgendwer eine Idee wie ich das löse?

Beste Grüße

**Comment by niclashoyer** [comment]
Analog zu #65 müsste in dem Abschnitt

```xml
<argument name="at_label" xsi:type="string">Delivery Time </argument>
```

nur `translate="true"` hinzugefügt werden, also so:

```xml
<argument name="at_label" xsi:type="string" translate="true">Delivery Time </argument>
```

Steht das in der XML wirklich mit Leerzeichen am Ende? Also "Delivery Time "? Das dann auch noch auf ohne Leerzeichen abändern.

**Comment by Moppelfett** [comment]
Top, hat geklappt.

Ja, das Leerzeichen stand so drin. Hatte es aus dem Code kopiert.

@niclashoyer BESTEN DANK!!!.
