### ISSUE TITLE
Are you sure you would like to remove this item from the shopping cart?

### ISSUE THREAD

**Issue by Moppelfett** [splendidinternet/Magento2_German_LocalePack_de_DE#67]
Hi Freunde,
Die in der Betreff stehenden Zeile wird leider beim löschen eines Artikels nicht mit übersetzt.

Der Code in minicart.js ist wie folgt:
`confirmMessage': $.mage.__(
                'Are you sure you would like to remove this item from the shopping cart?'
            )
        });`

In der de_DE.xml habe ich
"Are you sure you would like to remove this item from the shopping cart?","Willst Du diesen Artikel wirklich aus Deinem Warenkorb löschen?"
hinterlegt.
Leider ohne Funktion.
Kann mir hier einer helfen?

Besten Dank vorab.

**Comment by niclashoyer** [comment]
Scheint auch wieder ein bekanntes Problem zu sein, siehe hier: https://github.com/magento/magento2/issues/5893#issuecomment-267110081

**Comment by Moppelfett** [comment]
@niclashoyer 
Leider funktioniert die dort beschriebene "Beschreibung" nicht.
Es zeigt mir den Text immer noch auf Englisch. :-(

**Comment by niclashoyer** [comment]
Ist seit Magento 2.1 behoben, ein weiterer Workaround via CSS wurde in dem Magento-Repo beschrieben (s.o.).
