### ISSUE TITLE
"Sections have been updated"

### ISSUE THREAD

**Issue by Streetec** [splendidinternet/Magento2_German_LocalePack_de_DE#68]
Habe gerade die deutsche Übersetzung installiert und bin vollkommend zufrieden, allerdings ist mir noch eine Sache aufgefallen welche wohl noch nicht übersetzt wurde.

• Layered Navigation:
--> Nach setzen des Filters wird folgende Nachricht angezeigt: [Imgur link](http://i.imgur.com/RXBDdTn.png)

**Comment by felixbuechner** [comment]
Übersetzung ist jetzt drin.
