### ISSUE TITLE
Checkout Übersetzung noch unvollständig

### ISSUE THREAD

**Issue by Moppelfett** [splendidinternet/Magento2_German_LocalePack_de_DE#70]
Moin!
Diese zwei Sätze in der shipping-estimation.html werden nicht übersetzt.

`<p class="field note" data-bind="text: isVirtual ? $t('Enter your billing address to get a tax estimate.') : $t('Enter your destination to get a shipping estimate.')"></p>`

Hat jemand  eine schnelle Lösung für mich dies zu fixen (Shop ist in EN und DE)?
Wir gehen am 01.04. Online und da bleibt mir leider sehr wenig Zeit.
Vielen Dank für jede Hilfe!
Beste Grüße

**Comment by niclashoyer** [comment]
Wir können das Problem mit Magento 2.2 nicht mehr nachvollziehen. Falls das Problem aktuell noch besteht, bitte ein neues Issue öffnen.
