### ISSUE TITLE
Magento 2.1.5 Component Manager funktioniert nach Installation nicht mehr

### ISSUE THREAD

**Issue by Yunus260** [splendidinternet/Magento2_German_LocalePack_de_DE#71]
Hallo,

nachdem ich dieses Sprachpaket mit Composer installiert habe, hat im Magento Backend der Component Manager nicht mehr funktioniert. Es wird eine Dauerschleife "Loading" angezeigt. In der Chrome Konsole gab es einen 500 Fehler, der auf angular.js zurückzuführen ist.

Magento CE 2.1.5
Ich habe eine saubere Magento Installation mit dem Composer durchgeführt, diesen getestet - alles hat einwandfrei funktioniert. Anschließend NUR mithilfe von composer dieses Sprachpaket installiert und unmittelbar danach den Component Manager erneut getestet - Dauerschleife.

**Comment by niclashoyer** [comment]
Das Problem ist (leider) bekannt, siehe #42 
Es ist ein Bug in Magento, siehe https://github.com/magento/magento2/issues/6718
Der Fix wurde anscheinend noch nicht released.
