### ISSUE TITLE
Fehler Übersetzung

### ISSUE THREAD

**Issue by rorou** [splendidinternet/Magento2_German_LocalePack_de_DE#72]
In der Zeile 7275 hat sich ein funktionaler Fehler eingeschlichen, der den eigentlichen Inhalt verfälscht bzw. nicht korrekt darstellt:

Faslch: The order was placed using %1.,Die Bestellung wurde aufgegeben mit 1%.
Richtig: The order was placed using %1.,Die Bestellung wurde aufgegeben mit %1.

Somit wird die Währung, in der die Bestellung getätigt wurde, richtig angezeigt.

**Comment by niclashoyer** [comment]
@felixbuechner kannst du das übernehmen?

**Comment by felixbuechner** [comment]
Ist korrigiert.
