### ISSUE TITLE
Viele Punkte sind noch nicht übersetzt

### ISSUE THREAD

**Issue by marcmmx** [splendidinternet/Magento2_German_LocalePack_de_DE#76]
Viele Punkte sind noch nicht übersetzt, wie z.B. unter Neues Kundenkonto anlegen:
Password
Confirm Password
This is a required field.
Im Dashboard:
Store Payment Methods
usw.

**Comment by MichaelKahl** [comment]
This is a required field. -> ist teilweise im Code hardcodiert

Alles Andere wurde übersetzt
