### ISSUE TITLE
Selbst übersetzen?

### ISSUE THREAD

**Issue by Gamewalker** [splendidinternet/Magento2_German_LocalePack_de_DE#77]
Hallo,
ich schaffe es einfach nicht das aktuelle Paket zu nehmen und die fehlenden Sachen hinzuzufügen. Wie muss ich vorgehen um das Language Paket zu ergänzen oder die Fehlenden Einträge über mein Theme zur Verfügung zu stellen?`Egal was ich mache, ich kriege alle Strings ohne die bereits getätigte Übersetzung angezeigt.

**Comment by jdinse** [comment]
Hast du schon für die Sprache deployed?

`bin/magento setup:static-content:deploy -l de_DE`

**Comment by niclashoyer** [comment]
Das `bin/magento setup:static-content:deploy -l de_DE` sollte reichen nachdem die CSV-Datei geändert wurde.

Um die Änderungen auch hier im Repo einzustellen gibt es jetzt hier die Anleitung in der Readme: https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE#add-new-phrases
