### ISSUE TITLE
Einige Cart-Messages wird immer mit deutschem Message überschrieben

### ISSUE THREAD

**Issue by davidmonichi** [splendidinternet/Magento2_German_LocalePack_de_DE#79]
Habe das splendidinternet de installiert in einer frischen Magento 2.1.6 Installation installiert und die Übersetzung funktioniert wunderbar. Wenn ich es aber in einer Installation installiere wo ich vorher Daten aus Magento 1.7.1.2 migriert habe so werden bestimmte Messages immer mit der Deutschen Variante überschrieben.
Egal welche Sprache ich konfiguriere ich bekomme immer "Sie haben keine Artikel im Warenkorb" statt "You have no items in your shopping cart.".
Mache ich was falsch? Verwende die composer installation wie hier beschrieben. Habs mit Magento 2.1.7 auch schon versucht.

Da ich mir nicht sicher bin ob es ein Magento-Bug oder ein Überssetzungsproblem dieses Packets ist, habe ich auf Magento auch eine Frage erstellt.
https://magento.stackexchange.com/questions/177459/translation-magento-2-1-splendidinternet-de-overrides-cart-messages

**Comment by niclashoyer** [comment]
Kannst du es mit Magento 2.2 nochmal versuchen? Ich könnte mir auch vorstellen, dass teilweise Übersetzungen aus der Datenbank geladen werden, oder das Migrationstool evtl. eigene Übersetzungen anlegt. Ggf. müssten wir dann bei Magento im Repo ein Issue aufmachen.
