### ISSUE TITLE
Add support for magento framework 101.x.x (M2.2)

### ISSUE THREAD

**Issue by will-b** [splendidinternet/Magento2_German_LocalePack_de_DE#89]
Update the composer requirements to allow installation Magento 2.2 vesions

**Comment by niclashoyer** [comment]
I just added the 101.x.x version range, please check. Note that we are still in the progress of updating all the translations for 2.2.

**Comment by will-b** [comment]
Awesome, was able to install it with magento community 2.2.0-rc23 now. danke schön
