### ISSUE TITLE
Already translated but not visible strings

### ISSUE THREAD

**Issue by aschrammel** [splendidinternet/Magento2_German_LocalePack_de_DE#94]
As mentioned in PR #92 there are numerous translations that are already made but not translated in Backend (create/edit product) in Magento 2.2 RC 2.3:

* "Product Name"
* "Tax Class" and in the dropdown "Taxable Goods"
* "Advanced Inventory" and "Done" in "Erweitertes Inventar" overlay
* "Weight"
* "Visibility"
* "Categories" and in the dropdown checkbox "Default Category"
* "Content" and in this group "Description" and "Short Description"
* "When you remove or add an attribute, we automatically update all configurations and you will need to recreate current configurations manually." hint in "Konfiguration erstellen" overlay
* "Search Engine Optimization" and in this group "URL Key", "Meta Title", "Meta Keywords" and "Meta Description"
* Help popup text in "Produkte in Websites" group
* "Display Product Options In" and "Layout Update XML" in "Design" group
* "Schedule Design Update" and in this group "New Theme" and "New Layout"
* "Gift Options" and inside this group "Allow Gift Message"

Best regards,
Andreas

**Comment by MichaelKahl** [comment]
Product Name, Tax Class, Weight, Visibility, Categories, Description, Short Description, URL Key, Meta Title, Meta Keywords, Meta Description, New Theme, New Layout, Allow Gift Message, Display Product Options In und Layout Update XML sind Labels der Produktattribute

Taxable Goods ist der Name einer Steuerregel
Default Category ist ein Kategoriename
Content, Search Engine Optimization,Schedule Design Update und  Gift Options ist der Name der Gruppe eines Attributsets.

Advanced Inventory , Done -> erledigt
When you remove or add an attribute, we automatically update all configurations and you will need to recreate current configurations manually. -> erledigt

Help popup text in "Produkte in Websites" group -> erledigt
