### ISSUE TITLE
Fehlerhafte Übersetzung

### ISSUE THREAD

**Issue by daniel-rosengarten** [splendidinternet/Magento2_German_LocalePack_de_DE#98]
Im Dashboard steht "Durschschnittlicher Bestellumsatz", was in "Durchschnittlicher Bestellumsatz" geändert werden müsste.

**Comment by Schrank** [comment]
@daniel-rosengarten Das kannst du ganz einfach selbst machen:

# Einfach in die Datei gehen

![bildschirmfoto 2017-11-12 um 15 04 46](https://user-images.githubusercontent.com/379680/32699801-b9a5be66-c7bb-11e7-9e56-81760f371000.png)

# Oben rechts auf editieren klicken

![bildschirmfoto 2017-11-12 um 15 04 59](https://user-images.githubusercontent.com/379680/32699802-b9bdfde6-c7bb-11e7-9e12-64580f128f18.png)

# Kurze Beschreibung + Propose change

![bildschirmfoto 2017-11-12 um 15 05 41](https://user-images.githubusercontent.com/379680/32699799-b7bc040c-c7bb-11e7-8c6c-ee0793e7645a.png)

# Create pull request

![bildschirmfoto 2017-11-12 um 15 06 00](https://user-images.githubusercontent.com/379680/32699797-b1f3c4ec-c7bb-11e7-903a-a90246609c0b.png)

**Comment by jg-development** [comment]
I think this can be closed ... already fixed
